CREATE TABLE ITEM (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    PRICE REAL NOT NULL,
    CATEGORY VARCHAR(32) NOT NULL
);

INSERT INTO ITEM (ID, NAME, PRICE ,CATEGORY)
VALUES( 0, "Coca-Cola" , 100, "GENERAL");
INSERT INTO ITEM (ID, NAME, PRICE  ,CATEGORY)
VALUES( 1, "Sprite" , 150, "GENERAL");
INSERT INTO ITEM (ID, NAME, PRICE  ,CATEGORY)
VALUES( 2, "Fanta" , 300, "GENERAL");